[package]
name = "mod-scanner-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
yara-x = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
zip = "0.6"
sha2 = "0.10"
